services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    init: true
    env_file:
      - ./.env
    depends_on:
      - database
  database:
    image: sqlite:latest
    volumes:
      - db_data:/data
    restart: unless-stopped
volumes:
  db_data: